// Channel Transfer envelope codec. Mirrors `02-server/CHANNEL_TRANSFER_SPEC.md`
// v2.0 (biz_type 19/20) and `07-application/BOT_INTERACTION_SPEC.md`.
//
// `body` and `data` are opaque bytes — per-route encoding is decided by the
// application layer. This codec does NOT touch the inner bytes.
//
// `request_id` is generated by the originator (client for client→app, application
// for app→user push). Caller-supplied to keep idempotency under SDK control.

import * as flatbuffers from 'flatbuffers';
import {
  TransferRequest as FbTransferRequest,
} from '../generated/privchat/protocol/transfer-request.js';
import {
  TransferResponse as FbTransferResponse,
} from '../generated/privchat/protocol/transfer-response.js';
import { bigintToIdString, idStringToBigint } from './ids.js';

export interface TransferRequest {
  /** UUID v4 or equivalent ≥16-byte entropy, length ≤64. */
  request_id: string;
  /** Target channel id (string at API surface; u64 on wire). */
  channel_id: string;
  /** `{service}/{module}/{action}`; route prefix must == service.name. */
  route: string;
  /** Opaque request body; route-defined encoding. */
  body: Uint8Array;
}

export interface TransferResponse {
  /** Echo of the matching TransferRequest.request_id. */
  request_id: string;
  /** Echo of the matching TransferRequest.channel_id (string). */
  channel_id: string;
  /** Application-defined status (0 = OK). See ERROR_CODE_SPEC + CHANNEL_TRANSFER_SPEC §15. */
  code: number;
  message: string;
  /** None == empty payload (encoded as zero-length [ubyte] on the wire). */
  data?: Uint8Array;
}

export function encodeTransferRequest(msg: TransferRequest): Uint8Array {
  const builder = new flatbuffers.Builder(256);
  const requestIdOffset = builder.createString(msg.request_id);
  const routeOffset = builder.createString(msg.route);
  const bodyOffset = FbTransferRequest.createBodyVector(builder, msg.body);
  const offset = FbTransferRequest.createTransferRequest(
    builder,
    requestIdOffset,
    idStringToBigint(msg.channel_id),
    routeOffset,
    bodyOffset,
  );
  builder.finish(offset);
  return builder.asUint8Array();
}

export function decodeTransferRequest(bytes: Uint8Array): TransferRequest {
  const view = FbTransferRequest.getRootAsTransferRequest(
    new flatbuffers.ByteBuffer(bytes),
  );
  return {
    request_id: view.requestId() ?? '',
    channel_id: bigintToIdString(view.channelId()),
    route: view.route() ?? '',
    body: view.bodyArray() ?? new Uint8Array(0),
  };
}

export function encodeTransferResponse(msg: TransferResponse): Uint8Array {
  const builder = new flatbuffers.Builder(256);
  const requestIdOffset = builder.createString(msg.request_id);
  const messageOffset = builder.createString(msg.message);
  // None encodes as empty [ubyte]; decoder distinguishes by length.
  const dataOffset = FbTransferResponse.createDataVector(
    builder,
    msg.data ?? new Uint8Array(0),
  );
  const offset = FbTransferResponse.createTransferResponse(
    builder,
    requestIdOffset,
    idStringToBigint(msg.channel_id),
    msg.code,
    messageOffset,
    dataOffset,
  );
  builder.finish(offset);
  return builder.asUint8Array();
}

export function decodeTransferResponse(bytes: Uint8Array): TransferResponse {
  const view = FbTransferResponse.getRootAsTransferResponse(
    new flatbuffers.ByteBuffer(bytes),
  );
  const data = view.dataArray() ?? new Uint8Array(0);
  return {
    request_id: view.requestId() ?? '',
    channel_id: bigintToIdString(view.channelId()),
    code: view.code(),
    message: view.message() ?? '',
    data: data.length === 0 ? undefined : data,
  };
}
